function [x,w] = calc_p_ins_and_omega(in)
  global PREC;
  if PREC == 'single'
    single_format;

    x = [ ...
      in(:,UNPCKHPS) ...
      in(:,UNPCKLPS) ...
      in(:,SHUFPS) ...
      in(:,ADDSS) ...
      in(:,SUBSS) ...
      in(:,ADDPS) ...
      in(:,SUBPS) ...
      in(:,MOVSSM) ...
      in(:,MOVAPSM) ...
      in(:,MOVHPSM) ...
      in(:,MOVLPSM) ...
      in(:,MOVAPS) ...
    ];


    l = [
      UNPCKHPS_LAT ...
      UNPCKLPS_LAT ...
      SHUFPS_LAT ...
      ADDSS_LAT ...
      SUBSS_LAT ...
      ADDPS_LAT ...
      SUBPS_LAT ...
      MOVSSM_LAT ...
      MOVAPSM_LAT ...
      MOVHPSM_LAT ...
      MOVLPSM_LAT ...
      MOVAPS_LAT ...
    ];


    t = [
      UNPCKHPS_THP ...
      UNPCKLPS_THP ...
      SHUFPS_THP ...
      ADDSS_THP ...
      SUBSS_THP ...
      ADDPS_THP ...
      SUBPS_THP ...
      MOVSSM_THP ...
      MOVAPSM_THP ...
      MOVHPSM_THP ...
      MOVLPSM_THP ...
      MOVAPS_THP ...
    ];

    n = [
      UNPCKHPS_NUM ...
      UNPCKLPS_NUM ...
      SHUFPS_NUM ...
      ADDSS_NUM ...
      SUBSS_NUM ...
      ADDPS_NUM ...
      SUBPS_NUM ...
      MOVSSM_NUM ...
      MOVAPSM_NUM ...
      MOVHPSM_NUM ...
      MOVLPSM_NUM ...
      MOVAPS_NUM ...
    ];
  end

  w =  n ./ (l + ((n - 1) .* t)) ;
