#ifndef CONFIG_H
#define CONFIG_H

#ifndef SPLIT_MAX_FACTORS
#define SPLIT_MAX_FACTORS 40
#endif/*SPLIT_MAX_FACTORS*/

#ifndef CODELET_MAX_ARGUMENTS
#define CODELET_MAX_ARGUMENTS 3
#endif/*CODELET_MAX_ARGUMENTS*/

#ifndef MAX_UNROLLED
#define MAX_UNROLLED 8
#endif/*MAX_UNROLLED*/

#ifndef CODELET_NAME_MAX_SIZE
#define CODELET_NAME_MAX_SIZE 10
#endif/*CODELET_NAME_MAX_SIZE*/

#endif/*CONFIG_H*/
