#!/usr/bin/env ruby

# query
#
# Author: Michael Andrews <mjand@drexel.edu>
# $Id$

require 'utils'

def index(plans)
  index = {} 
  plans.each do |k,v|
    uniq = [v['oid'], v['plan'], v['transform']].join(':')
    index[uniq] = v
  end
  return index
end

def die
  puts "query: FILE "
  exit 1
end

if __FILE__ == $0
  die if ARGV.size < 1
  data = ARGV[0]

  env = load_runtime_env
  info, plans = load_data(data, env)

  plans = index(plans)

  save_data(data, env, plans, info)
end
