#!/usr/bin/env ruby

# query
#
# Author: Michael Andrews <mjand@drexel.edu>
# $Id$

# TODO matlab or CSV style 

require 'utils'

def die
  puts "query: FILE SELECT [WHERE]"
  exit 1
end

if __FILE__ == $0
  die if ARGV.size < 2
  input   = ARGV[0]
  selects = ARGV[1].split(/\s*,\s*/)
  where   = ARGV[2]
  
  re = where.nil? ? nil : Regexp.new('^\d+\s*:\s*.*?:\s*' + where + '$')

  env   = load_runtime_env
  info, plans = load_data(input, env)

  # Place header
  hostname = `hostname`
  puts "% HOSTNAME #{hostname}"
  env.each { |key,value| puts "% #{key} #{value}" }
  puts "% WHERE  : #{where}"
  puts "% SELECT : " + selects.join(', ')

  out = {}

  plans.each do |key, node|
    next unless re.nil? or key =~ re

    oid = node['oid'].to_i
    row = Array.new(selects.size)

    node.each do |key,value|
      i = selects.index(key)
      next if i.nil?
      row[i] = value
    end

    out[oid] = row

  end

  out.sort.each do |oid, value|
    puts value.join(' ')
  end

end
