#!/usr/bin/env ruby

$LOAD_PATH << File.dirname(__FILE__) 

require 'utils'

def search(a,b,n,k,kp,file,root,rules)
  if rules.empty?
    r = ''
  else
    r = "-r '#{rules.join(':')}'"
  end
  cmd = "./wht_dp -k #{kp} -a #{a} -b #{b} #{r} -f '#{root}/#{file}' -m '#{BIN_PATH}/wht_measure -k #{k} -n #{n} -a 0.5 -p 0.1 -e PAPI -m TOT_CYC' -v"
  puts cmd
  IO.popen(cmd) do |fd|
    while (line = fd.gets)
      puts line
      $stdout.flush
    end
  end
end

def run(spec)
  spec["runs"].each do |file, rules|
    spec["params"].each do |p|
      search(p["a"], p["b"], p["n"] , p["k"], p["kp"], file, spec["root"], rules)
    end
  end
end

def die
  puts "wht_search: SPEC"
  exit 1
end

if $0 == __FILE__
  die if ARGV.size < 1

  spec = load_data(ARGV[0],{})

  time {
    puts "running ..."
    run(spec["search"])
    puts "total"
  }

end

