#!/usr/bin/env bash

function usage() 
{
  echo "Usage: wht_vectorize -w WHT_PLAN -k INTERLEAVE -v VECTOR_SIZE [-c]"
  exit 1
}

path=`dirname $0`

plan=''

v=2 # Vector size
k=2 # Interleave parameter
c=0 # Compose with smaller functions ?

while getopts "k:w:v:ch" i; do
  case "$i" in
    "w") plan=$OPTARG;
    ;;
    "k") k=$OPTARG;
    ;;
    "v") v=$OPTARG;
    ;;
    "c") c=1
    ;;
    "h")
      usage;
    ;;
    *)
      usage;
    ;;
  esac
done

if [ "$plan" == "" ]; then
  read plan
fi

attach="${path}/../bin/wht_attach"

plan=`${attach} -w ${plan} -r splitil[small[0]]`

args="smallv($v)[0]"
plan=`${attach} -w ${plan} -r $args`

if [ $c = 1 ]; then
  for ((i=k;i>=2;i/=2)); do
    args="smallv($v,$i,1)[0]"
    plan=`${attach} -w ${plan} -r $args`
  done

  for ((i=k;i>=2;i/=2)); do
    args="smallv($v,$i,0)[0]"
    plan=`${attach} -w ${plan} -r $args`
  done
else
  args="smallv($v,$k,1)[0]"
  plan=`${attach} -w ${plan} -r $args`
  args="smallv($v,$k,0)[0]"
  plan=`${attach} -w ${plan} -r $args`
fi

echo ${plan}
