#!/usr/bin/env perl

use vars qw/ %opt /;
use Getopt::Std;
use File::Basename qw/ dirname /;

$path       = dirname($0);

$call       = "apply_spiral";
$interface  = "Wht *W, long S, size_t U, wht_value *x";

$opts = 'n:';
getopts($opts, \%opt);

sub usage {
 print "spiral2wht: -n SIZE DIRECTORY\n";
 exit;
}

$size  = $opt{n} || usage;

$code_path = $ARGV[0] || $path;

@files = <$code_path/*.c>;

$codelet = "";

# Find file with appropriate size
foreach $file (@files) {
  open(FD, $file) or die "Could not open $file to read.";
  while ($line = <FD>) {
    if ($line =~ /void WHT_(\d+).*/) {
      if ((1 << $size) == $1) {
        $codelet = $file;
        last;
      }
    }
  }
  close(FD);
}

if ($codelet eq "") {
  print "Could not find SPIRAL codelet of size $size\n";
  exit;
}

# Convert SPIRAL function to WHT function
open(FD, $codelet) or die "Could not open $codelet to read.";
print "#include \"wht.h\"";

while ($line = <FD>) {
  next if $line =~ /^#include/; # Skip SPIRAL includes

  if ($line =~ /void WHT_(\d+).*/) {
    $size = (log($1) / log(2));
  }

  $line =~ s/void WHT_(\d+).*/void $call\_$size($interface) {/;
  $line =~ s/(double)|(float)/wht_value/;
  $line =~ s/X/x/;
  $line =~ s/Y/x/;

  print $line;
}

close(FD);

