/* Small WHT
   ---------
   Unrolled building blocks from the library libwht.a,
   which are generated by whtgen.
*/

#include "wht.h"
#include "codelets.h"

char *
small_to_string(Wht *W)
{
  const size_t bufsize = 10; /*small[%2d]\0*/
  char *buf;

  buf = wht_malloc(sizeof(char) * bufsize);
  snprintf(buf, bufsize, "small[%zd]", W->n);
  return buf;
}

Wht *
wht_init_small(size_t n)
{
  Wht *W;
  const size_t bufsize = 15; /*apply_small%2d\0*/
  char buf[bufsize]; 

  if (n > WHT_MAX_UNROLL)
    wht_error("not configured for unrolled codelets of size %zd", n);

  snprintf(buf,bufsize,"apply_small%zd",n);

  W            = wht_init_codelet(n);
  W->apply     = wht_get_codelet(buf);
  W->to_string = small_to_string;

  if (W->apply == NULL)
    wht_error("could not find codelet %s", buf);

  return W;  
}

Wht **
small_family(size_t n)
{
  Wht **Ws;
  
  Ws = wht_malloc(sizeof(*Ws) * WHT_MAX_FAMILY);

  Ws[0] = wht_init_small(n);
  Ws[1] = NULL;

  return Ws;
}


