#include "wht.h"
#include "registry.h"

/* Defined in parser.c which is generated by parser.y  */
extern Wht *wht_root;

Wht *
wht_parse(char *in)
{
  Wht *wht;

  yy_scan_string(in);
  yyparse();
  wht = wht_root;

  return wht;
}

void
codelet_guard(Wht *W, size_t right)
{
  /* Empty */
}

Wht *
codelet_init(int n, char *name)
{
  Wht *W;

  W            = (Wht *) wht_malloc(sizeof(Wht));
  W->N         = (1 << n); 
  W->n         = n;
  W->free      = codelet_free;
  W->apply     = NULL;
  W->guard     = codelet_guard;
  W->name      = name;

  W->attr[interleave_by] = 1;

  return W;  
}

void 
codelet_free(Wht *W) 
{
  wht_free(W);
}

void
wht_info(void)
{
  printf("CC: %s\n", WHT_CC);
  printf("CFLAGS: %s\n", WHT_CFLAGS);
  printf("type: %s\n", WHT_TYPE_STRING);
  printf("max_unroll: %d\n", WHT_MAX_UNROLL);
  printf("max_interleave: %d\n", WHT_MAX_INTERLEAVE);
  printf("vector_size: %d\n", WHT_VECTOR_SIZE);
}


split_init_fp
lookup_split(const char *name, size_t params)
{
  split_init_entry *p;

  for (p = (split_init_entry *) splits_registry; p != NULL && (split_init_fp) p->call != NULL; ++p)
    if ((strncmp(name, p->name, MAX_CODELET_NAME_SIZE) == 0) && (params == p->params))
      return p->call;
  return NULL;
}

small_init_fp
lookup_small(const char *name, size_t params)
{
  small_init_entry *p;

  for (p = (small_init_entry *) smalls_registry; p != NULL && (small_init_fp) p->call != NULL; ++p)
    if ((strncmp(name, p->name, MAX_CODELET_NAME_SIZE) == 0) && (params == p->params))
      return p->call;
  return NULL;
}

