#!/usr/bin/env ruby

# whtgen.rb
#
# Author: Michael Andrews <mjand@drexel.edu>
# $Id$
#
# TODO increment ref count when tmp is input
#      decrement ref count when tmp is output
#      reuse tmps that have 0 ref count
#
#      add macro guards for unrolled codelets
#      add macro guards for interleaved codelets

INDENT   = "  "

def log2(n)
  (Math.log(n) / Math.log(2)).to_i
end

def l_mn_m(m,n)
  p = []
  for i in 0 .. (m-1) do
    for j in 0 .. (n-1) do
      p << (j*m)+i
    end
  end
  p
end

def permute(n,x,a,s,y,b,t,v,sign)
  p = l_mn_m(n/2,2)
   
  t1,t2 = mk_tmp(2)
  if    p ==  [0,2,1,3] and v == 2
    @stack.push Shuf.new(t1,x[a],x[a+s],[0,0],v)
    @stack.push Shuf.new(t2,x[a],x[a+s],[1,1],v)
  elsif p ==  [0,2,1,3] and v == 4
    @stack.push Shuf.new(t1,x[a],x[a+s],[0,1,0,1],v)
    @stack.push Shuf.new(t2,x[a],x[a+s],[2,3,2,3],v)
  elsif p ==  [0,4,1,5,2,6,3,7] and v == 4 and sign > 0
    @stack.push Shuf.new(t1,x[a],x[a+s],[0,1,0,1],v)
    @stack.push Shuf.new(t2,x[a],x[a+s],[2,3,2,3],v)
    @stack.push Shuf.new(t1,t1,t1,[0,2,1,3],v)
    @stack.push Shuf.new(t2,t2,t2,[0,2,1,3],v)
  elsif p ==  [0,4,1,5,2,6,3,7] and v == 4 and sign < 0
    @stack.push Shuf.new(x[a],x[a],x[a],[0,2,1,3],v)
    @stack.push Shuf.new(x[a+s],x[a+s],x[a+s],[0,2,1,3],v)
    @stack.push Shuf.new(t1,x[a],x[a+s],[0,1,0,1],v)
    @stack.push Shuf.new(t2,x[a],x[a+s],[2,3,2,3],v)
  end
  y[b],y[b+t] = t1,t2
end

def wht_2v(n,x,a,s,y,b,t,v)
  p,q,r = {}, {}, {}
  m = n/2
  wht_2(x,a,s,p,b,t,v)

  permute(n,p,a,s,q,b,t,v,+1)

  if m > 2
    wht_2v(m,q,a,s,r,b,t,v)
  else
    wht_2(q,a,s,r,b,t,v)
  end

  permute(n,r,a,s,y,b,t,v,-1)
end

def wht_2(x,a,s,y,b,t,v)
  t1,t2 = mk_tmp(2)
  @stack.push Add.new(t1,x[a],x[a+s],v)
  @stack.push Sub.new(t2,x[a],x[a+s],v)
  y[b],y[b+t] = t1,t2
end

def wht(n,x,a,s,y,b,t,v)
  if n < 2 # Transform undefined, just copy input to output
    y[b],y[b+s] = x[a],x[a+s]
  elsif n == 2
    wht_2(x,a,s,y,b,t,v)
  elsif n == 2*v
    wht_2v(n,x,a,s,y,b,t,v)
  else
    z = {}
    m = n/2
    wht(m,x,a,s,z,b,t,v)
    wht(m,x,a+(m/v),s,z,b+(m/v),t,v)

    for i in 0 .. (m/v)-1 do
      wht_2(z,a+i,(m/v)*s,y,b+i,(m/v)*t,v)
    end
  end
end

class BinIns
  attr_accessor :v
  def initialize(r,a,b,v)
    @r,@a,@b,@v = r,a,b,v
    @t = 'ta'
  end

  def interleave(k)
    k.times { @t = @t.succ }
  end

  def tmps
    [(sprintf "%s%d",@t,@r),
     (sprintf "%s%d",@t,@a), 
     (sprintf "%s%d",@t,@b), ]
  end
end

class Add < BinIns
  def to_s
    if @v < 2 
      "#{@t}#{@r} = #{@t}#{@a} + #{@t}#{@b};\n"
    else
      "vadd#{@v}(#{@t}#{@r},#{@t}#{@a},#{@t}#{@b});\n"
    end
  end
end

class Sub < BinIns
  def to_s
    if @v < 2 
      "#{@t}#{@r} = #{@t}#{@a} - #{@t}#{@b};\n"
    else
      "vsub#{@v}(#{@t}#{@r},#{@t}#{@a},#{@t}#{@b});\n"
    end
  end
end

class Shuf < BinIns
  def initialize(r,a,b,m,v)
    # TODO assert m.size = v
    super(r,a,b,v)
    @m = m
  end

  def to_s
    if @v < 2 
      "/* undefined*/;\n"
    else
      "vshuf#{@v}(#{@t}#{@r},#{@t}#{@a},#{@t}#{@b},#{@m.join(',')});\n"
    end
  end
end

class MemIns
  attr_accessor :v
  def initialize(r,m,s,a,v)
    @r,@m,@s,@a,@v = r,m,s,a,v
    @k = 0
    @t = 'ta'
  end

  def interleave(k)
    @k = k
    k.times { @t = @t.succ }
  end

  def stride
    @a ? "#{@s+@k}" : "#{@s} * S + #{@k}"
  end

  def tmps
    [(sprintf "%s%d",@t,@r)]
  end
end

class Load < MemIns
  def to_s
    if @v < 2 
      sprintf "%s%d = %s[%s];\n",@t,@r,@m,stride
    else
      sprintf "vload%d(%s%d,%s[%s]);\n",@v,@t,@r,@m,stride
    end
  end
end

class Store < MemIns
  def to_s
    if @v < 2 
      sprintf "%s[%s] = %s%d;\n",@m,stride,@t,@r
    else
      sprintf "vstore%d(%s%d,%s[%s]);\n",@v,@t,@r,@m,stride
    end
  end
end

class Generator
  def initialize(n,i,v,vp,a,type,name)
    @n,@i,@v,@vp,@a,@type,@name = n,i,v,vp,a,type,name
    @stack  = []
    @tmp    = 0
  end

  def mk_tmp(k=1)
    return @tmp += 1 unless k > 1

    a = []
    k.times do
      a << @tmp += 1
    end
    a
  end

  def compile_guard
    g = []
    g << "(#{log2(@n)} <= WHT_MAX_UNROLL)"
		g << "(#{log2(@i)} <= WHT_MAX_INTERLEAVE)" if @i > 1
		g << "(#{@vp} == WHT_VECTOR_SIZE)"   if @vp > 1
    "#if " + g.join(" && ") + "\n"
  end

  def to_s
    body = ""
    tmps = []
    @stack.each do |x|
      body += INDENT + x.to_s
      tmps += x.tmps
    end

    a = @a ? '_a' : ''

    header  = "#include \"wht.h\"\n\n" +
              "void #{@name}#{a}(Wht *W, long S, wht_value *x)\n{\n"

		header += compile_guard

    decls = ""
    tmps.uniq.each do |t|
      decls += sprintf "%s%s %s;\n",INDENT, @type, t
    end

		# TODO add else / error macro guard
    footer  = ""
    footer += "#else\n   wht_error(\"initialization guards should prevent this message\");\n" 
		footer += "#endif\n"
    header + decls + body + footer + "}\n"
  end

  def interleave
    q = []
    @stack.each do |x|
      q << x.clone
      for k in 1 .. @i-1 do # Make i copies
        y = x.clone
        y.interleave(k)
        q << y
      end
    end
    @stack = q
  end

  def vectorize(v)
    p = []
    (0..@stack.size-1).step(v) do |i|
      x = @stack[i]
      x.v = v
      p << x
    end
    @stack = p
  end

  def run
    x = {}
    y = {}

    @n.times do |i| 
      t = mk_tmp
      x[i] = t
      @stack.push  Load.new(t,"x",(i*@v),@a,@v)
    end

    wht(@n*@v,x,0,1,y,0,1,@v)

    @n.times do |i| 
      t = y[i] 
      @stack.push Store.new(t,"x",(i*@v),@a,@v)
    end

    interleave
  end
end

def die(msg)
  puts msg
  exit 1
end

# Main entry point 

class Options
  require 'optparse'
  attr_reader :params
  def initialize
    @params = {}
    @params[:n] = nil
    @params[:v] = 1
    @params[:a] = false
    @params[:i] = 1
    @options = OptionParser.new do |o|
      o.banner = "Usage: #{$0} [OPTIONS]"
      o.separator ""
      o.on("-h", "--help", 
        "Show this help message.") { die }

      o.on("-v", "--vector_size=SIZE", Integer,
        "Vector size.") { |x| @params[:v] = x.to_i }

      o.on("-n", "--wht_size=SIZE", Integer,
        "Size of WHT to unroll.") { |x| @params[:n] = x.to_i } 

      o.on("-a", "--aligned", 
        "Access aligned memory, i.e. at unit stride.") { |x| @params[:a] = true }

      o.on("-i", "--interleave=FACTOR", Integer,
        "Loop interleaving factor.") { |x| @params[:i] = x.to_i } 
    end
  end

  def die(msg = nil)
    puts @options.to_s 
    puts "\n#{msg}" unless msg.nil?
    exit
  end

  def parse(args)
    begin
      @options.parse!(args)
    rescue => e
      die(e.message)
    end

    die unless @params[:n]

    @params[:n] = 2**@params[:n]
    unless @params[:n]*@params[:i] > @params[:v]
      die("Size*Interleaved must be greater than vector size.")
    end
  end

end

if $0 == __FILE__ 
  opts = Options.new
  opts.parse(ARGV)

  n = opts.params[:n]
  v = opts.params[:v]
  i = opts.params[:i]
  a = opts.params[:a] 
  m = (Math.log(n) / Math.log(2)).to_i

  if v > 1 and i > 1 
    g = Generator.new(n,i,1,v,a,"wht_vector#{v}", "apply_small#{m}_v#{v}_il#{i}")
    g.run
    g.vectorize(v)
  elsif v > 1
    g = Generator.new((n/v),1,v,v,a,"wht_vector#{v}", "apply_small#{m}_v#{v}")
    g.run
  elsif i > 1
    g = Generator.new(n,i,1,1,a,"wht_value", "apply_small#{m}_il#{i}")
    g.run
  else
    g = Generator.new(n,1,1,1,a,"wht_value", "apply_small#{m}")
    g.run
  end

  puts g
end
