/*
 * Copyright (c) 2000 Carnegie Mellon University
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

/** 
 * \file whtgen/whtgen.c 
 *
 * \brief Simple generator for unrolled codelets of the form 
 * \f$ {\bf WHT}_{N} \otimes {\bf I}_{S} \f$.  
 *
 * Algorithm is to 
 * generate code is iterative, and only two temporaries are used.
 *
 * \code
 *  N1 = N/2;
 *  N2 = 1;
 *  for (i = 1; i <= N; i *= 2) {
 *    for (j = 0; j < N1; j++) {
 *      for (k = 0; k < N2; k++) {
 *        ind1 = (j * 2 * N2 + k) * s;
 *        ind2 = (j * 2 * N2 + N2 + k) * s;
 *        for (l = 0; l < s; l++) {
 *          a       = x[ind1];
 *          b       = x[ind2];  
 *          x[ind1] = a + b;
 *          x[ind2] = a - b;
 *          ind1++;
 *          ind2++;
 *        }
 *      }
 *    }
 *    N1 /= 2;
 *    N2 *= 2;
 *  }
 * \endcode
 */

/** \cond */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>

static void
usage() 
{
  printf("Usage: whtgen -n SIZE \n\n");
  printf("    -h            Show this help message.\n");
  printf("    -n SIZE       Generate codelet of size N=2^SIZE.\n");
  printf("\n");
  exit(1);
}

int 
main(int argc, char *argv[])
{
  int n;
  char c;

  n = 0;

  opterr = 0;

  while ((c = getopt (argc, argv, "hn:")) != -1)
    switch (c) {
      case 'n':
        n = atoi(optarg);
        break;
      case 'h':
        usage();
      default:
        usage();
    }

  if (n < 1)
    usage();

  long N1, N2, i, j, l;
  int N;

  N = (1 << n);

  /* Header */
  printf("/* This file has been automatically generated by whtgen/whtgen.c. */\n");
  printf("\n");

  /* Meta Data */
  printf("/*\n");
  printf("EXTERNS: {\n");
  printf("extern codelet_apply_fp apply_small%d;\n", n);
  printf("}\n");
  printf("STRUCTS: {\n");
  printf("#if (%d <= WHT_MAX_UNROLL)\n", n);
  printf("CODELET_APPLY_ENTRY(\"small[%d]\", apply_small%d),\n", n, n);
  printf("#endif\n");
  printf("}\n");
  printf("*/\n");
  printf("\n");

  /* Includes */
  printf("#include \"wht.h\"\n");
  printf("\n");

  /* Function Signature */
  printf("void apply_small%d(Wht *W, long S, long U, wht_value *x)\n", n);
  printf("{\n");

  /* Compile guard */
  printf("#if (%d <= WHT_MAX_UNROLL)\n", n);

  /* Declarations */
  printf("  wht_value a, b;\n");
 
  /* Body */
  N1 = N/2;
  N2 = 1;
  for (i = 1; i <= N; i *= 2) {
    for (j = 0; j < N1; j++) {
      for (l = 0; l < N2; l++) {
        printf("  a = x[%ld * S];\n", j * 2 * N2 + l);
        printf("  b = x[%ld * S];\n", j * 2 * N2 + N2 + l);
        printf("  x[%ld * S] = a + b;\n", j * 2 * N2 + l);
        printf("  x[%ld * S] = a - b;\n", j * 2 * N2 + N2 + l);
      }
    }
    N1 /= 2;
    N2 *= 2;  
  }

  /* Compile guard */
  printf("#else\n");
  printf("   wht_exit(\"runtime guards should prevent this message\");\n");
  printf("#endif\n");

  /* Footer */
  printf("}\n"); 
  return 0;
}
/** \endcond */
